# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "a1",
  "description": "Датчик где?"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/8/
Content-Type: application/json

{
  "description": "Он в ванной"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 22.3
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/1/
Content-Type: application/json
